worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;
    tcp_nopush on;

    server {
        listen 80;

        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;

        location / {
            if ($request_method = OPTIONS) {
                return 204;
            }
            proxy_pass http://app:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 120s;
            proxy_send_timeout 120s;
            client_max_body_size 35m;
        }

        location /protected_files/ {
            internal;
            alias /var/www/artifacts/;
        }
    }
}
