-- INIT UP

CREATE TABLE components (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE builds (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_id INT NOT NULL,
    name VARCHAR(50) NOT NULL,

    CONSTRAINT fk_build_component
        FOREIGN KEY (component_id)
        REFERENCES components(id)
        ON DELETE CASCADE
);

CREATE TABLE test_suites (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE run_statuses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE result_statuses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE file_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE test_runs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    build_id INT NOT NULL,
    suite_id INT NOT NULL,
    status_id INT NOT NULL,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_run_build
        FOREIGN KEY (build_id)
        REFERENCES builds(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_run_suite
        FOREIGN KEY (suite_id)
        REFERENCES test_suites(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_run_status
        FOREIGN KEY (status_id)
        REFERENCES run_statuses(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_run_time
        CHECK (finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at)
);

CREATE TABLE test_artifacts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id INT NOT NULL,
    status_id INT NOT NULL,
    file_url VARCHAR(500) NOT NULL,
    file_type_id INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_artifact_run
        FOREIGN KEY (run_id)
        REFERENCES test_runs(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_artifact_status
        FOREIGN KEY (status_id)
        REFERENCES result_statuses(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_artifact_file_type
        FOREIGN KEY (file_type_id)
        REFERENCES file_types(id)
        ON DELETE RESTRICT
);

CREATE TABLE user_groups (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    group_id INT,
    is_active BOOLEAN DEFAULT TRUE,
    is_ldap BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_user_group
        FOREIGN KEY (group_id)
        REFERENCES user_groups(id)
        ON DELETE SET NULL
);
