basePath: /
definitions:
  analytics.DayCount:
    properties:
      count:
        type: integer
      date:
        type: string
    type: object
  analytics.StatusCount:
    properties:
      count:
        type: integer
      status:
        type: string
    type: object
  models.ArtifactInfo:
    properties:
      build:
        type: string
      component:
        type: string
      downloadURL:
        type: string
      fileName:
        type: string
      fileSize:
        format: int64
        type: integer
      id:
        format: int64
        type: integer
      suite:
        type: string
      uploadTime:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API для системы хранения артефактов автотестов.
  title: Test Storage API
  version: "1.0"
paths:
  /:
    get:
      description: Отображает главную HTML-страницу для авторизованного пользователя.
      produces:
      - text/html
      responses:
        "200":
          description: HTML-страница
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Главная страница
      tags:
      - general
  /analytics:
    get:
      description: Возвращает страницу с аналитикой в виде графиков.
      produces:
      - application/json
      responses:
        "200":
          description: HTML-страница
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Страница аналитики
      tags:
      - analytics
  /analytics/artifacts-per-day:
    get:
      description: Возвращает агрегированные данные о количестве загруженных артефактов
        с группировкой по дням.
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ
          schema:
            items:
              $ref: '#/definitions/analytics.DayCount'
            type: array
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Количество артефактов по дням
      tags:
      - analytics
  /analytics/status-distribution:
    get:
      description: Возвращает распределение прогонов по статусам (Passed, Failed).
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ
          schema:
            items:
              $ref: '#/definitions/analytics.StatusCount'
            type: array
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Распределение статусов тестовых прогонов
      tags:
      - analytics
  /artifact/download/{id}:
    get:
      description: Скачивает файл артефакта по его ID.
      parameters:
      - description: ID артефакта
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/octet-stream
      responses:
        "200":
          description: Файл артефакта
          schema:
            type: file
        "400":
          description: Некорректный ID
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Артефакт не найден
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Скачать артефакт
      tags:
      - artifacts
  /artifacts:
    get:
      description: Возвращает список артефактов в формате JSON, с возможностью фильтрации
        по компоненту, сборке, набору тестов и временному диапазону.
      parameters:
      - description: Название компонента
        in: query
        name: component
        type: string
      - description: Номер сборки
        in: query
        name: build
        type: string
      - description: Название тестового набора
        in: query
        name: suite
        type: string
      - description: Начальная граница времени загрузки (RFC3339)
        in: query
        name: from
        type: string
      - description: Конечная граница времени загрузки (RFC3339)
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список артефактов
          schema:
            items:
              $ref: '#/definitions/models.ArtifactInfo'
            type: array
        "400":
          description: Некорректные параметры запроса
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Список артефактов с фильтрацией
      tags:
      - artifacts
  /health/alive:
    get:
      description: Возвращает статус "alive", если сервис работает.
      produces:
      - application/json
      responses:
        "200":
          description: Alive
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Проверка, жив ли сервис
      tags:
      - health
  /health/ready:
    get:
      description: Проверяет доступность БД и других зависимостей.
      produces:
      - application/json
      responses:
        "200":
          description: Ready
          schema:
            additionalProperties:
              type: string
            type: object
        "503":
          description: Not ready
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Проверка готовности сервиса
      tags:
      - health
  /login:
    get:
      description: Отображает HTML-страницу с формой для входа в систему.
      produces:
      - text/html
      responses:
        "200":
          description: HTML-страница входа
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Страница входа
      tags:
      - auth
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Аутентифицирует пользователя по логину и паролю из HTML-формы.
      parameters:
      - description: Логин
        in: formData
        name: username
        required: true
        type: string
      - description: Пароль
        in: formData
        name: password
        required: true
        type: string
      responses:
        "303":
          description: Редирект на главную страницу
        "400":
          description: Плохой запрос
          schema:
            type: string
        "401":
          description: Неверные учетные данные
          schema:
            type: string
      summary: Войти в систему
      tags:
      - auth
  /logout:
    post:
      description: Завершает сеанс пользователя и перенаправляет на страницу входа.
      responses:
        "303":
          description: Редирект на /login
        "405":
          description: Метод не разрешен
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Выйти из системы
      tags:
      - auth
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: Загружает в систему файл артефакта и метаданные.
      parameters:
      - description: Файл артефакта
        in: formData
        name: file
        required: true
        type: file
      - description: Тестируемый компонент
        in: query
        name: component
        required: true
        type: string
      - description: Номер сборки
        in: query
        name: build
        required: true
        type: string
      - description: Набор тестов
        in: query
        name: suite
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "201":
          description: Файл успешно загружен
          schema:
            type: string
        "400":
          description: Ошибка в запросе
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Загрузить файл
      tags:
      - upload
swagger: "2.0"
